### ISSUE TITLE
[Streaming 指南] 模块翻译认领

### ISSUE THREAD

**Issue by wuchong** [flink-china/flink-china-doc#1]
有想认领章节的请在下方回复。

在 `apis/streaming` 目录下
- ~~[index.md](http://doc.flink-china.org/apis/streaming/)~~    @wuchong
- ~~[fault_tolerance.md](http://doc.flink-china.org/apis/streaming/fault_tolerance.html)~~  @darionyaphet 
- ~~[savepoints.md](http://doc.flink-china.org/apis/streaming/savepoints.html)~~ @aspoman 
- ~~[state.md](http://doc.flink-china.org/apis/streaming/state.html)~~ @unsleepy22
- ~~[state_backends.md](http://doc.flink-china.org/apis/streaming/state_backends.html)~~ @unsleepy22
- [storm_compatibility.md](http://doc.flink-china.org/apis/streaming/storm_compatibility.html) @darionyaphet 
- [time.md](http://doc.flink-china.org/apis/streaming/time.html)  
- [windows.md](http://doc.flink-china.org/apis/streaming/windows.html)
- connectors
  - ~~[index.md](http://doc.flink-china.org/apis/streaming/connectors/)~~ @wuchong
  - [elasticsearch.md](http://doc.flink-china.org/apis/streaming/connectors/elasticsearch.html) @aspoman 
  - [hdfs.md](http://doc.flink-china.org/apis/streaming/connectors/hdfs.html)  @aspoman 
  - ~~[kafka.md](http://doc.flink-china.org/apis/streaming/connectors/kafka.html)~~   @wuchong
  - [rabbitmq.md](http://doc.flink-china.org/apis/streaming/connectors/rabbitmq.html)
  - [twitter.md](http://doc.flink-china.org/apis/streaming/connectors/twitter.html)
- libs
  - [cep.md](http://doc.flink-china.org/apis/streaming/libs/cep.html)
  - [index.md](http://doc.flink-china.org/apis/streaming/libs/)

**Comment by darionyaphet** [comment]
@wuchong  这些是你自己都完成了？还是只有index是你认领了的呢？ 我也是初学flink 想翻译一个 :dancer:

**Comment by wuchong** [comment]
@darionyaphet 只有index 我完成了， 后面的我都还没有认领 。 有人认领的，我会在后面 @ 他的名字。翻译完成的会划掉。

你可以找一个感兴趣的翻译 :smile:

**Comment by darionyaphet** [comment]
我想尝试翻译一个 `fault_tolerance.md`  晚上翻译 尽量在今天完成 :)

**Comment by wuchong** [comment]
@darionyaphet  赞

**Comment by aspoman** [comment]
savepoints.md 这个我来试着翻译下

**Comment by wuchong** [comment]
@aspoman  好的

**Comment by unsleepy22** [comment]
state.md和state_backends.md这两篇我来翻译

**Comment by aspoman** [comment]
elasticsearch.md 再来翻一篇，争取少点翻译错误

**Comment by darionyaphet** [comment]
@wuchong storm_compatibility.md  storm我用过 这个我翻译吧

**Comment by aspoman** [comment]
hdfs.md 翻译一篇这个

**Comment by lmalds** [comment]
我来翻译window这一节吧@wuchong

**Comment by wuchong** [comment]
@lmalds  好的
