### ISSUE TITLE
[安装] 模块翻译认领

### ISSUE THREAD

**Issue by wuchong** [flink-china/flink-china-doc#12]
`setup` 目录下
- ~~[building.md](http://doc.flink-china.org/setup/building.html)~~  @darionyaphet 
- [config.md](http://doc.flink-china.org/setup/config.html)   @darionyaphet 

部署
- ~~[local_setup.md](http://doc.flink-china.org/setup/local_setup.html)~~ @wuchong
- ~~[cluster_setup.md](http://doc.flink-china.org/setup/cluster_setup.html)~~ @wuchong
- ~~[yarn_setup.md](http://doc.flink-china.org/setup/yarn_setup.html)~~  @wuchong
- ~~[gce_setup.md](http://doc.flink-china.org/setup/gce_setup.html)~~  @darionyaphet 
- [jobmanager_high_availability.md](http://doc.flink-china.org/setup/jobmanager_high_availability.html) @darionyaphet

**Comment by darionyaphet** [comment]
mark :dancer:

**Comment by darionyaphet** [comment]
我觉得我应该从最简单的开始逐步翻译 上来就翻译容错这种重量级的组件有点儿云里雾里 Orz 申请 `building.md`

**Comment by wuchong** [comment]
@darionyaphet  好的

**Comment by darionyaphet** [comment]
@wuchong 在认领一个 `config.md`  谢谢:)

**Comment by wuchong** [comment]
@darionyaphet  好的

**Comment by darionyaphet** [comment]
@wucong   gce_setup.md  翻译已提交  谢谢 :)

**Comment by darionyaphet** [comment]
@wuchong jobmanager_high_availability.md 翻译申请 谢谢

**Comment by taizilongxu** [comment]
@darionyaphet  config.md 这个我来吧
