### ISSUE TITLE
[快速起步] 模块翻译认领

### ISSUE THREAD

**Issue by wuchong** [flink-china/flink-china-doc#13]
`quickstart` 目录下
- ~~[setup_quickstart.md](http://doc.flink-china.org/quickstart/setup_quickstart.html)~~
- [run_example_quickstart.md](http://doc.flink-china.org/quickstart/run_example_quickstart.html) @hustfxj 
- ~~[java_api_quickstart.md](http://doc.flink-china.org/quickstart/java_api_quickstart.html)~~  @litongbupt 
- ~~[scala_api_quickstart.md](http://doc.flink-china.org/quickstart/scala_api_quickstart.html)~~  @RominYue

**Comment by RominYue** [comment]
还剩一篇，scala_api_quikstart.md? 我来翻译吧

**Comment by wuchong** [comment]
@RominYue  好的

**Comment by wuchong** [comment]
quickstart 翻译完成  closed

**Comment by wuchong** [comment]
官网更新的 quickstart 的 example ， 从原来的batch 例子改成了 streaming 例子。

@hustfxj  有没有兴趣再翻译一下？  你原来翻译的被顶掉了 :joy:

**Comment by darionyaphet** [comment]
@wuchong  Flink 是release 一个版本 snapshot一个版本么？

**Comment by wuchong** [comment]
@darionyaphet 是的。我们翻译的话尽量跟的最新版本。等翻译完了， 会冻结。然后开新分支跟最新版本。

**Comment by darionyaphet** [comment]
还要跟着官网更新 逐步更新文档翻译

**Comment by wangyangjun** [comment]
@wuchong run_example_quickstart.md 我来吧
