### ISSUE TITLE
[编程指南] 模块翻译认领

### ISSUE THREAD

**Issue by wuchong** [flink-china/flink-china-doc#14]
在 `apis` 目录下
- ~~[common](http://doc.flink-china.org/apis/common/)~~
- batch   传送门 #2 
- streaming  传送门 #1 
- ~~[connectors.md](http://doc.flink-china.org/apis/connectors.html)~~
- [best_practices.md](http://doc.flink-china.org/apis/best_practices.html)
- ~~[cli.md](http://doc.flink-china.org/apis/cli.html)~~ @Astralidea 
- [local_execution.md](http://doc.flink-china.org/apis/local_execution.html)  @Astralidea 
- [cluster_execution.md](http://doc.flink-china.org/apis/cluster_execution.html)
- [scala_shell.md](http://doc.flink-china.org/apis/scala_shell.html)
- [java8.md](http://doc.flink-china.org/apis/java8.html)
- ~~index.md  不用翻译~~
- ~~programming_guide.md  不用翻译~~
- ~~streaming_guide.md 不用翻译~~

**Comment by Astralidea** [comment]
cli.md 认领

**Comment by Astralidea** [comment]
local_execution.md 认领

**Comment by taizilongxu** [comment]
metric.md 认领下
