### ISSUE TITLE
[内部] 模块翻译认领

### ISSUE THREAD

**Issue by wuchong** [flink-china/flink-china-doc#15]
在 `internals`  目录下
- [ide_setup.md](http://doc.flink-china.org/internals/ide_setup.html)
- [logging.md](http://doc.flink-china.org/internals/logging.html)
- [general_arch.md](http://doc.flink-china.org/internals/general_arch.html)
- [stream_checkpointing.md](http://doc.flink-china.org/internals/stream_checkpointing.html)  @bakey 
- [types_serialization.md](http://doc.flink-china.org/internals/types_serialization.html)
- [monitoring_rest_api.md](http://doc.flink-china.org/internals/monitoring_rest_api.html)
- [job_scheduling.md](http://doc.flink-china.org/internals/job_scheduling.html)
- [add_operator.md](http://doc.flink-china.org/internals/add_operator.html)
- ~~_draft_distributed_akka.md 不用翻译~~
- ~~coding_guidelines.md 不用翻译~~
- ~~how_to_contribute.md 不用翻译~~
- ~~index.md 不用翻译~~

**Comment by bakey** [comment]
stream_checkpointing.md 认领这个

**Comment by bakey** [comment]
文档中的 "exactly-once" 和 "at least once" 这两个地方我保持英文原文。大家觉得可以不？

**Comment by wuchong** [comment]
@bakey  可以。 另外你也可以 `恰好一次（exactly-once）`   和 `至少一次（at lease once）`  这样翻译。

**Comment by bakey** [comment]
@wuchong OK

**Comment by bakey** [comment]
按照我们公司内部的说法是，不重不丢（exactly-once）和 可重不丢(at least once)。大家可参考下

**Comment by unsleepy22** [comment]
exactly-once和at-least-once保持原文吧  @bakey @wuchong

**Comment by wuchong** [comment]
@unsleepy22  可以。 

那我待会儿更新下READEME， 以后的就不要翻译 exactly-once 了。

**Comment by bakey** [comment]
提交了一个PR
