### ISSUE TITLE
fault_tolerance translate

### ISSUE THREAD

**Issue by darionyaphet** [flink-china/flink-china-doc#19]
translate [fault_tolerance](http://doc.flink-china.org/apis/streaming/fault_tolerance.html) into chinese :)

**Comment by darionyaphet** [comment]
translate [fault_tolerance](http://doc.flink-china.org/apis/streaming/fault_tolerance.html) into chinese :)

**Comment by wuchong** [comment]
Translation completed?  But I can't find the PR.  :cold_sweat:

**Comment by darionyaphet** [comment]
@wuchong I push this PR just moment please see here : [#21](https://github.com/flink-china/flink-china-doc/pull/21)

**Comment by darionyaphet** [comment]
不好意思哈 昨天晚上翻译完了之后 怎么也push不上去 中间总是断 你懂得  ...
