### ISSUE TITLE
[Batch  指南] 模块翻译认领

### ISSUE THREAD

**Issue by wuchong** [flink-china/flink-china-doc#2]
有想认领章节的请在下方回复。

在 `apis/batch` 目录下
- ~~[index.md](http://doc.flink-china.org/apis/batch/)~~  @longdafeng 
- ~~[iterations.md](http://doc.flink-china.org/apis/batch/iterations.html)~~ @longdafeng 
- ~~[dataset_transformations.md](http://doc.flink-china.org/apis/batch/dataset_transformations.html)~~ @longdafeng 
- ~~[examples.md](http://doc.flink-china.org/apis/batch/examples.html)~~ @longdafeng 
- ~~[fault_tolerance.md](http://doc.flink-china.org/apis/batch/fault_tolerance.html)~~ @longdafeng 
- ~~[hadoop_compatibility.md](http://doc.flink-china.org/apis/batch/hadoop_compatibility.html)~~ @longdafeng 
- ~~[python.md](http://doc.flink-china.org/apis/batch/python.html)~~ @longdafeng 
- ~~[zip_elements_guide.md](http://doc.flink-china.org/apis/batch/zip_elements_guide.html)~~ @longdafeng 
- libs
  - [index.md](http://doc.flink-china.org/apis/batch/libs/)
  - [gelly.md](http://doc.flink-china.org/apis/batch/libs/gelly.html)
  - [table.md](http://doc.flink-china.org/apis/batch/libs/table.html)
  - ml @unsleepy22 
    - [index.md](http://doc.flink-china.org/apis/batch/libs/ml/)
    - ~~[als.md](http://doc.flink-china.org/apis/batch/libs/ml/als.html)~~
    - [contribution_guide.md](http://doc.flink-china.org/apis/batch/libs/ml/contribution_guide.html)
    - ~~[distance_metrics.md](http://doc.flink-china.org/apis/batch/libs/ml/distance_metrics.html)~~
    - ~~[min_max_scaler.md](http://doc.flink-china.org/apis/batch/libs/ml/min_max_scaler.html)~~
    - ~~[multiple_linear_regression.md](http://doc.flink-china.org/apis/batch/libs/ml/multiple_linear_regression.html)~~
    - [optimization.md](http://doc.flink-china.org/apis/batch/libs/ml/optimization.html)
    - [pipelines.md](http://doc.flink-china.org/apis/batch/libs/ml/pipelines.html)
    - [polynomial_features.md](http://doc.flink-china.org/apis/batch/libs/ml/polynomial_features.html)
    - [quickstart.md](http://doc.flink-china.org/apis/batch/libs/ml/quickstart.html)
    - ~~[standard_scaler.md](http://doc.flink-china.org/apis/batch/libs/ml/standard_scaler.html)~~
    - ~~[svm.md](http://doc.flink-china.org/apis/batch/libs/ml/svm.html)~~  @fengjian428

**Comment by unsleepy22** [comment]
ml这块我来翻译吧

**Comment by wuchong** [comment]
@unsleepy22 ml 模块这么多呢 ，先选个几篇呗。

**Comment by fengjian428** [comment]
被你领了呀 早知道不翻了

**Comment by darionyaphet** [comment]
才发现Flink release 1.0版本了   各位转战[Apache Flink](http://flink.apache.org/) 了？

**Comment by wuchong** [comment]
@darionyaphet   刚 release 的 1.0 版本。  

学习 Flink ， 不要与国外的领先技术脱轨

**Comment by darionyaphet** [comment]
@wuchong 可以在 readme 上面加一个index么 方便跳转到各个模块 也能知道哪些模块还没有翻译:)

**Comment by wuchong** [comment]
@darionyaphet  目前是到 http://doc.flink-china.org 上看，仍旧是英文的则是没有翻译的。然后再来issue 看有没有人认领。  我待会儿会再开几个issue 把每个模块的文章列一下，方便大家认领。

**Comment by darionyaphet** [comment]
thanks for you great work :)

**Comment by longdafeng** [comment]
iterations.md     @longdafeng
dataset_transformations.md  @longdafeng
examples.md                         @longdafeng
fault_tolerance.md                @longdafeng
hadoop_compatibility.md      @longdafeng
python.md                             @longdafeng
zip_elements_guide.md        @longdafeng

**Comment by darionyaphet** [comment]
@longdafeng V587
