### ISSUE TITLE
有没有翻译Spark官方文档的计划

### ISSUE THREAD

**Issue by darionyaphet** [flink-china/flink-china-doc#24]
公司在用spark 最近一直在学习 有没有翻译Spark官方文档的计划  

感觉spark在国内发展时间也不短了 文档资料很多 或许没必要吧 :)

**Comment by wuchong** [comment]
spark 的官方文档翻译已经有很多了。大部分是个人翻译的，并发编程网最近也在组织翻译。 不过他们的翻译形式不像我们，最后出来的形式是类似博客形式的，所以体验会差些。
