### ISSUE TITLE
overview 领取

### ISSUE THREAD

**Issue by longdafeng** [flink-china/flink-china-doc#3]

**Comment by wuchong** [comment]
是指 http://flink.apache.org/features.html 和 http://flink.apache.org/index.html 吗？

这两个页面不在文档中， 不过可以翻译完后，我加到中文文档里。

**Comment by darionyaphet** [comment]
其他的都是md文件  这两个是html的 需要转成md文件么？

**Comment by wuchong** [comment]
@darionyaphet    feature 的我已经翻译完成了，见[这个链接](http://doc.flink-china.org/features.html)。  这两个页面是在这个项目里的，  http://github/apache/flink-web   ，flink官方文档中不包括这两个页面。

**Comment by wuchong** [comment]
我觉得 http://flink.apache.org/ 这个overview 页面翻译的意义不是很大。 文档的首页也有个类似的overview，内容差不多。

所以我把这个 issue 关闭啦
