### ISSUE TITLE
请问项目还在维护吗?

### ISSUE THREAD

**Issue by taizilongxu** [flink-china/flink-china-doc#42]
貌似issue都非常久远了

**Comment by longdafeng** [comment]
在维护啊， 你什么问题呢

另外这个项目主要是翻译文档， 大部分东西，我们已经完成了

2016-09-21 10:45 GMT+08:00 hackerxu <notifications@github.com>:

**Comment by taizilongxu** [comment]
哦哦, 有一些没翻译的我去认领几个
