### ISSUE TITLE
1.2版本的更新什么时候会跟进呢

### ISSUE THREAD

**Issue by T-baby** [flink-china/flink-china-doc#47]
如题，我看到官方在今年已经发布了1.2版本，不知道什么时候能够跟进呢？

**Comment by wuchong** [comment]
@T-baby , 1.2版本的翻译已经进行了大半了，1.2版本的翻译放在 https://github.com/Apache-Flink-Docs-ZH/Apache-Flink-Docs-ZH-translation 这个仓库中进行，感兴趣的话可以参与
