### ISSUE TITLE
单词翻译问题

### ISSUE THREAD

**Issue by alastairruhm** [flink-china/flink-china-doc#49]
编程模型 - 窗口 一节中的 time driven 被翻译为「事件驱动」，是否应该翻译为「时间驱动」？

原文：https://ci.apache.org/projects/flink/flink-docs-release-1.4/concepts/programming-model.html#windows

> Windows can be time driven (example: every 30 seconds) or data driven (example: every 100 elements).

**Comment by ruoyou** [comment]
好的，我们来校正一下。翻译的问题可以在这里讨论哈：https://github.com/flink-china/Flink-China-Translate-Team-/issues。方便加下微信么，我拉你到我们的翻译群里，我的微信：zzzz1025zzzz。

**Comment by alastairruhm** [comment]
十分抱歉，我主职不是搞大数据的，所以就不参与翻译了。
