### ISSUE TITLE
页面跳转错误

### ISSUE THREAD

**Issue by zshnb** [flink-china/flink-china-doc#50]
现在左边导航栏部分链接点击失效了，只有首页和快速起步能跳转，其余均无法点击跳转

**Comment by zacharyzhanghao** [comment]
我刚才试了下，确实有这个问题，有人解决吗？

**Comment by 857681664** [comment]
这个可能没有在维护了吧，目前估计只能看官方文档了

**Comment by ruoyou** [comment]
那个导航栏，发个链接？

**Comment by 857681664** [comment]
刚才上去看了一下，发现又恢复正常了，感谢你们修复了这个问题

**Comment by hhaiben123** [comment]
http://doc.flink-china.org/latest/
中文文档有时候进不去

**Comment by hhaiben123** [comment]
http://doc.flink-china.org/latest/#collapse-11
有时候点了左侧也进不去

**Comment by CarryChang** [comment]
https://flink-china.org/ 站点失效了，能不能修复一下
